on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0 # Fetch all history for tags and releases

      - name: Setup Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.11'

      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}


  deploy:
    if: needs.release-please.outputs.release_created == 'true'
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install Rye
        uses: eifinger/setup-rye@787604a465b1696ad17eedf2f8101df9fc555c94 # v2
        with:
          enable-cache: true
      - name: Rye Sync
        run: rye sync --no-lock
      - name: Rye Build
        run: rye build
      - name: Rye Publish
        run: rye publish --token ${{ secrets.PYPI_API_TOKEN }} --yes
